### ISSUE TITLE
Under Blender 4.3, getting an error with orphan_widgets

### ISSUE THREAD

**Issue by FranckyB** [techartorg/bqt#125]
Under Blender 4.2, our Pipeline Widget seems to work without error, but under Blender 4.3, the same Widget causes error.

The error is:
> Traceback (most recent call last):
>   File "\\fs01\env\packages\blender\base_config\addons\bqt\blender_applications\blender_application.py", line 83, in on_update
>     bqt.manager.parent_orphan_widgets(exclude=[self.blender_widget, self._blender_window, self.window_container])  # auto parent any orphaned widgets
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "\\fs01\env\packages\blender\base_config\addons\bqt\manager.py", line 181, in parent_orphan_widgets
>     for widget in _orphan_toplevel_widgets():
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "\\fs01\env\packages\blender\base_config\addons\bqt\manager.py", line 170, in _orphan_toplevel_widgets
>     return [widget for widget in QApplication.instance().topLevelWidgets() if
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "\\fs01\env\packages\blender\base_config\addons\bqt\manager.py", line 171, in <listcomp>
>     not widget.parent()
>         ^^^^^^^^^^^^^^^
> TypeError: 'NoneType' object is not callable

**Comment by hannesdelbeke** [comment]
i can only assume QApplication.instance().topLevelWidgets returns None for some reason, instead of the widget.
that's odd.

can you share the version of pyside you are using?

a workaround could be to disable autoparenting for now , see https://github.com/techartorg/bqt/wiki/Environment-variables

**Comment by FranckyB** [comment]
We are using pyside 2.
The environment Variable did the trick!
Would this prevent some functionality with this off?

Thanks

**Comment by hannesdelbeke** [comment]
yes since widgets are not parented, they will stay visible when you minimise blender.
and you now can alt tab to them as if they are another app.

to prevent that, you could manually parent them to the blender window.
i d have to dig in the code since it's not in the wiki. 
you can check out the parent function. i think the top level widget is saved in our QApplication as a variable if i remember correctly

**Comment by hannesdelbeke** [comment]
i v been using pyside 6 for development recently, might be worth seeing if that would resolve it.
since max and maya are also finally moving away from pyside 2

**Comment by FranckyB** [comment]
We had planned to use Maya 2024, as we had issues with 2025.
Trying just now to use Pyside6, I realize switching versions would also mean fixing a bunch of things in the code, as there are a bunch of small differences in PySide6.

For now, I'll turn off Auto Parenting and fix our pipeline to be pyside6 compatible eventually 😅
Thanks

**Comment by FranckyB** [comment]
Hi Hannes, so I've finally took the time to switch our pipline to pyside 6, but unfortunately this didn't change the error.
As you suggested, turning off Auto parenting did the trick and I'm simply making any new widget Stay on Top.

I don't particularly need a fix, but I thought I'd mention that Pyside 2 was not the issue.

On a side note, I really want to thank you for this addon!  
I've been able to port most of our Maya Pipeline to Blender and makes Blender so much more production suitable.  

I had worked previously on a project as a co-production, where I was introduced to Blender.  
The pipeline they had was limited to using only Blender's UI and was terrible because of that.

Your addon allows for Full customization of Blender and changes everything :)
This should really be part of Blender!

Thanks

**Comment by hannesdelbeke** [comment]
Thanks for letting me know, and for the kind words. 
I had the same experience as you with Blender, and with previous experience in Max & Maya knew what Blender was missing.
Sound like I need to have a look at the parenting issue again sometime.
