### ISSUE TITLE
Hello_World not working

### ISSUE THREAD

**Issue by Aiyush-G** [techartorg/bqt#18]
Hi all, 

I am getting this error and I was hoping that you could help?

```
>>> from bqt import hello_world
>>> hello_world.demo()
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bqt/hello_world.py", line 46, in demo
    main_window = QApplication.instance().blender_widget
AttributeError: 'NoneType' object has no attribute 'blender_widget'
```

Thanks
AG

**Comment by squindt** [comment]
same problem here, @Aiyush-G did you manage to resolve the issue?

**Comment by Aiyush-G** [comment]
Unfortunately no, what platform are you running on?

**Comment by squindt** [comment]
Windows

**Comment by knsii** [comment]
This is because the pywin32 dependency is not installed. 
https://github.com/techartorg/bqt/blob/8437e061b74f1a692ef16b2174144cf5e25120f2/setup.py#L91
Currently, you can make it work by manually installing pywin32.
