### ISSUE TITLE
missing bl_info dict

### ISSUE THREAD

**Issue by hannesdelbeke** [techartorg/bqt#52]
Has anyone else had problems with the latest bqt version?
Using 3.3LTS and the addon no longer has the bl_info dict which causes an error on start up

> slack chatlog: [Shea Richardson](https://tech-artists.slack.com/archives/C0F73KP2N/p1667477621371359?thread_ts=1667477288.103659&cid=C0F73KP2N)
> 
> I had to do some fix ups to get it functional for 3.3 LTS
> main one was this:
> https://tech-artists.slack.com/archives/C0F73KP2N/p1666962461134569
> Has anyone else had problems with the latest bqt version?
> Using 3.3LTS and the addon no longer has the bl_info dict which causes an error on start up
> could have been related to how we load auto-load our plugins
> it caused an infinite loop if it did not exist

reported by Shea Richardson
who will make a PR 🙏

**Comment by munkybutt** [comment]
Further info related to the error:
It occurs when enabling the addon progromatically using:
`addon_utils.enable`:

```
Traceback (most recent call last):
  File ".../blender/python/startup/startup.py", line 124, in _auto_enable_addons
    auto_enable_addons(addons_root_path)
  File ".../blender/python/startup/startup.py", line 87, in auto_enable_addons
    bpy.ops.wm.save_userpref()
  File "C:/Program Files/Blender Foundation/Blender 3.3/3.3/scripts/modules/bpy/ops.py", line 97, in __call__
    import bpy
  File "C:/Program Files/Blender Foundation/Blender 3.3/3.3/python/lib/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:/Program Files/Blender Foundation/Blender 3.3/3.3/scripts/modules/bpy/__init__.py", line 61, in <module>
    main()
  File "C:/Program Files/Blender Foundation/Blender 3.3/3.3/scripts/modules/bpy/__init__.py", line 58, in main
    utils.load_scripts()
  File "C:/Program Files/Blender Foundation/Blender 3.3/3.3/scripts/modules/bpy/utils/__init__.py", line 301, in load_scripts
    _initialize()
  File "C:/Program Files/Blender Foundation/Blender 3.3/3.3/scripts/modules/addon_utils.py", line 29, in _initialize
    enable(addon.module)
  File "C:/Program Files/Blender Foundation/Blender 3.3/3.3/scripts/modules/addon_utils.py", line 355, in enable
    if mod.bl_info.get("blender", (0, 0, 0)) < (2, 80, 0):
AttributeError: module 'bqt' has no attribute 'bl_info'
```

The fix is to re-add the `bl_info` dict to bqt `__init__.py` file:
```
bl_info = {
    "name": "Qt for Blender",
    "author": "Tech-Artists.org",
    "version": (0, 2),
    "blender": (2, 80, 3),
    "description": "Qt for Blender",
    "warning": "",
    "wiki_url": "",
}
```

**Comment by munkybutt** [comment]
Hey bud - yeah it is just the top level dict called `bl_info` that is required

**Comment by hannesdelbeke** [comment]
removed the leftover empty addon, finsihing the cleanup. closing this.
